### ISSUE TITLE
'list' object has no attribute 'items' ?

### ISSUE THREAD

**Issue by Dviros** [hatching/triage#1]
Hi there,
While trying to query for "201216-n8flt7hfgj", I get weird error message (maybe no attributes?) in both Windows and Ubuntu.

❯ triage report 201216-n8flt7hfgj
~Overview~
4803137295908864.zip
  md5: 87d7159d8532b8ffb830a296bd753026
  score: 10
  family: ['trickbot']
  tags: ['family:trickbot', 'botnet:lib688', 'banker', 'trojan']

Traceback (most recent call last):
  File "C:\Python39\Scripts\triage-script.py", line 33, in <module>
    sys.exit(load_entry_point('hatching-triage==0.1.1', 'console_scripts', 'triage')())
  File "c:\python39\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\python39\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\python39\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python39\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python39\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\python39\lib\site-packages\cli\triage.py", line 336, in report
    for k, task in r.get("tasks", {}).items():
AttributeError: 'list' object has no attribute 'items'

Please assist :)
Thanks!

**Comment by Evert0x** [comment]
Hi @Dviros , thank you for creating this issue.

I was able to reproduce and fix the issue. Please upgrade to the latest version (using `pip install -U hatching-triage`)

Please let me know if you encounter other issues.
