### ISSUE TITLE
When setting a wrong API URL : parsing error of the returned 404 error

### ISSUE THREAD

**Issue by goulou** [hatching/triage#7]
When setting a wrong URL (typically forgetting the "/api"..... ), the client (be it through CLI or via the Python) fails at parsing the response, since it gets a 404 error code. The content of the response is indeed `<Response [404]>`, which is not json-readable.

The `ServerError` should check the status_code before trying to unmarshall the response.
```
class ServerError(Exception):
    def __init__(self, err):
        b = err.response.json()
        self.status = err.response.status_code
        self.kind = b['error']
        self.message = b['message']
```

Full traceback below :
```
Traceback (most recent call last):
  File "/home/user/venvs/hatching/bin/triage", line 8, in <module>
    sys.exit(cli())
  File "/home/user/venvs/hatching/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/venvs/hatching/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/user/venvs/hatching/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/venvs/hatching/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/venvs/hatching/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/user/venvs/hatching/lib/python3.9/site-packages/cli/triage.py", line 226, in list_samples
    for i in c.public_samples(max=n) if public else c.owned_samples(max=n):
  File "/home/user/venvs/hatching/lib/python3.9/site-packages/triage/pagination.py", line 49, in __next__
    if not self._fetch_next_page():
  File "/home/user/venvs/hatching/lib/python3.9/site-packages/triage/pagination.py", line 31, in _fetch_next_page
    resp = self._client._req_json('GET', path)
  File "/home/user/venvs/hatching/lib/python3.9/site-packages/triage/client.py", line 49, in _req_json
    raise ServerError(err)
  File "/home/user/venvs/hatching/lib/python3.9/site-packages/triage/client.py", line 510, in __init__
    b = err.response.json()
  File "/home/user/venvs/hatching/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by RicoVZ** [comment]
Thanks for reporting this @goulou.
This should now be solved.
